- name: fetch frr source tree
  ansible.builtin.git:
    repo: '{{ frr_repository }}'
    dest: /root/frr

- name: configure group
  ansible.builtin.group:
    state: present
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
  with_items:
  - name: frr
    gid: 92
  - name: frrvty
    gid: 85

- name: configure user
  ansible.builtin.user:
    name: frr
    comment: "FRR suite"
    groups: frr,frrvty
    home: /var/run/frr
    system: true
    shell: /sbin/nologin
    append: yes

- name: build and install frr
  shell: |
    set -xe
    cd /root/frr
    ./bootstrap.sh
    ./configure \
      --prefix=/usr \
      --includedir=\${prefix}/include \
      --bindir=\${prefix}/bin \
      --sbindir=\${prefix}/lib/frr \
      --libdir=\${prefix}/lib/frr \
      --libexecdir=\${prefix}/lib/frr \
      --localstatedir=/var/run/frr \
      --sysconfdir=/etc/frr \
      --with-moduledir=\${prefix}/lib/frr/modules \
      --with-libyang-pluginsdir=\${prefix}/lib/frr/libyang_plugins \
      --enable-configfile-mask=0640 \
      --enable-logfile-mask=0640 \
      --enable-snmp=agentx \
      --enable-multipath=64 \
      --enable-user=frr \
      --enable-group=frr \
      --enable-sharpd \
      --enable-vty-group=frrvty \
      --with-pkg-git-version \
      --with-pkg-extra-version=-MyOwnFRRVersion
    make -j `nproc` && make -j `nproc` install

- name: install systemfiles
  shell: |
    set -xe
    cd /root/frr
    install -m 775 -o frr -g frr -d /var/log/frr
    install -m 775 -o frr -g frrvty -d /etc/frr
    install -m 640 -o frr -g frrvty tools/etc/frr/vtysh.conf /etc/frr/vtysh.conf
    install -m 640 -o frr -g frr tools/etc/frr/frr.conf /etc/frr/frr.conf
    install -m 640 -o frr -g frr tools/etc/frr/daemons.conf /etc/frr/daemons.conf
    install -m 640 -o frr -g frr tools/etc/frr/daemons /etc/frr/daemons
    install -m 644 tools/frr.service /etc/systemd/system/frr.service

- name: setup for topotest
  tags: hoge
  shell: |
    apt -y install mininet
    apt -y install iperf
    apt -y install gdb
    pip2 install ipaddr
    pip2 install "pytest<5"
    pip2 install "scapy>=2.4.2"
    pip2 install exabgp==3.4.17
    useradd -d /var/run/exabgp/ -s /bin/false exabgp
    /etc/init.d/openvswitch-switch start
